function demoConvNorm()
close all;clear;clc;
bigImageProcessed = uint8([ ...
    1 1 1; ...
    1 90 156; ...
    0 25 60 ...
    ]);
convCore = uint8([ ...
    2 2; ...
    0 9; ...
    ]);
bigImageProcessed = double(bigImageProcessed)/255;
convCore = double(convCore)/255;
convOutcome = convNorm(bigImageProcessed,convCore);

end